name: 'GBL Front 이슈 생성'
description: 'GBL Front Repo에 이슈를 생성하며, 생성된 이슈는 Jira와 연동됩니다.'
labels: [order]
title: 'feat-task'
body:

  - type: input
    id: jiratitle
    attributes:
      label: 'Jira 이슈 제목'
      description: 'Jira 이슈 제목을 기입해주세요'
      placeholder: 'Jira 이슈 제목'
    validations:
      required: true

  - type: input
    id: parentKey
    attributes:
      label: '상위 작업 Ticket Number'
      description: '상위 작업의 Ticket Number를 기입해주세요'
      placeholder: 'GBL-00'
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: '이슈 내용(Description)'
      description: '이슈에 대해서 간략히 설명해주세요'
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: '상세 내용(Details)'
      description: '이슈에 대해서 자세히 설명해주세요'
      value: |
        - About Details
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: '참조(References)'
      description: '해당 이슈과 관련된 레퍼런스를 참조해주세요'
      value: |
        - Reference1
    validations:
      required: false
